
# ImageNet poisons can be optimized in a similar way, although it requires much more time and resources to do so. 
# If you would like to attempt this, you can use the included info.pkl file. 
# This splits up the ImageNet dataset into subsets of 25k that can then be crafted one at a time (52 subsets in total). 
# Each subset can take anywhere from 1-3 days to craft depending on your GPU resources. You also need >200gb of storage to store the generated dataset.

CUDA_VISIBLE_DEVICES=2 python anneal.py --recipe targeted \
    --eps 8 --budget 1.0 --dataset ImageNet \
    --pretrained --poison_partition 25000 \
    --save poison_dataset \
    --poison_path /data2/wyw/sam/example/2024_07_30_UniG_reproduce/poison \
    --restarts 1 \
    --data_path /home/datasets/ILSVRC2012 \
    --pbatch 128 \
    --attackoptim PGD

# You can then evaluate the poisons you generated by running
# python poison_evaluation/main.py --load_path /path/to/your/saved/poisons --runs 1
# Where --load_path specifies the path to the generated poisons
# and --runs specifies how many runs to evaluate the poisons over. 
# This will test on a ResNet-18, but this can be changed by un-commenting the appropriate net in main.py
