####

CUDA_VISIBLE_DEVICES=1 python anneal.py \
    --net ResNet18 \
    --recipe targeted \
    --eps 8 --budget 1.0 \
    --save poison_dataset_cifar10 \
    --poison_path /data2/wyw/sam/example/2024_07_30_UniG_reproduce/poison \
    --attackoptim PGD

# You can then evaluate the poisons you generated by running
# python poison_evaluation/main.py --load_path /path/to/your/saved/poisons --runs 1
# Where --load_path specifies the path to the generated poisons
# and --runs specifies how many runs to evaluate the poisons over. 
# This will test on a ResNet-18, but this can be changed by un-commenting the appropriate net in main.py
